project_root = "../../.."
include(project_root.."/tools/build")

group("src")
project("xenia-kernel")
  uuid("ae185c4a-1c4f-4503-9892-328e549e871a")
  kind("StaticLib")
  language("C++")
  links({
    "aes_128",
    "fmt",
    "zlib-ng",
    "pugixml",
    "libcurl",
    "miniupnp",
    "xenia-apu",
    "xenia-base",
    "xenia-cpu",
    "xenia-hid",
    "xenia-vfs",
  })
  includedirs({
    project_root.."/third_party/libcurl/include",
    project_root.."/third_party/miniupnp/miniupnpc/include",
    project_root.."/third_party/rapidcsv/src",
    project_root.."/third_party/rapidjson/include",
  })
  defines({
    "X86_FEATURES",
    "X86_HAVE_XSAVE_INTRIN",
    "X86_SSSE3",
    "X86_SSE42",
    "WITH_GZFILEOP",
    "CURL_STATICLIB",
    "MINIUPNP_STATICLIB",
  })
  if os.istarget("windows") then
    defines({
      "X86_SSE2",
      "X86_AVX2",
      "X86_AVX512",
      "X86_AVX512VNNI",
      "X86_PCLMULQDQ_CRC",
      "X86_VPCLMULQDQ_CRC",
    })
  end
  recursive_platform_files()
  files({
    "debug_visualizers.natvis",
  })
